import { BankAccount, ExchangeRates } from '../types/dashboard';

export const INITIAL_RATES: ExchangeRates = {
  bcv: 853.50,
  bcvUsd: 853.50,
  bcvEur: 976.55,
  binanceP2p: 915.00,
  fechaValor: '',
  tasaUsdAnterior: 852.42,
  tasaEurAnterior: 978.17,
  fechaTasaAnterior: '',
  lastUpdated: new Date().toISOString(),
};

export const INITIAL_ACCOUNTS: BankAccount[] = [
  {
    id: 'bdv',
    bankId: 'bdv',
    bankName: 'BDV',
    bankShort: 'BDV',
    accountType: 'Cuenta Bancaria',
    accountNumber: '04129549022',
    nativeCurrency: 'VES',
    balanceNative: 0,
    lastSync: '',
    linkActualizar: 'https://trigger.macrodroid.com/25be1f4a-0ab8-459e-977c-a6b58d1d3edf/BDV',
  },
  {
    id: 'banesco',
    bankId: 'banesco',
    bankName: 'BANESCO',
    bankShort: 'BANESCO',
    accountType: 'Cuenta Bancaria',
    accountNumber: '04244909232',
    nativeCurrency: 'VES',
    balanceNative: 0,
    lastSync: '',
    linkActualizar: 'https://trigger.macrodroid.com/25be1f4a-0ab8-459e-977c-a6b58d1d3edf/BANESCO',
  },
  {
    id: 'bnc',
    bankId: 'bnc',
    bankName: 'BNC',
    bankShort: 'BNC',
    accountType: 'Cuenta Bancaria',
    accountNumber: '04129549022',
    nativeCurrency: 'VES',
    balanceNative: 0,
    lastSync: '',
    linkActualizar: 'https://trigger.macrodroid.com/25be1f4a-0ab8-459e-977c-a6b58d1d3edf/BNC',
  },
  {
    id: 'bdv-tu-combox-c-a',
    bankId: 'bdv-combox',
    bankName: 'BDV TU COMBOX C.A',
    bankShort: 'BDV TU COMBOX C.A',
    accountType: 'Cuenta Bancaria',
    accountNumber: 'J501298211',
    nativeCurrency: 'VES',
    balanceNative: 0,
    lastSync: '',
    linkActualizar: '',
  },
  {
    id: 'binance',
    bankId: 'binance',
    bankName: 'Binance',
    bankShort: 'BINANCE',
    accountType: 'ID',
    accountNumber: '1272204580',
    nativeCurrency: 'USD',
    balanceNative: 0,
    lastSync: '',
    linkActualizar: '',
  },
];
